# This is a very helpful youtube video: https://www.youtube.com/watch?v=GEunDyG_C54

title: Semicertain
description: This is the tagline.
author: Mikhail Schee
email: me@semicertain.com
#phone: (650) 576-5403
github: https://github.com/semicertain
about: This is a circular link back to <a href="https://www.semicertain.com" target="_blank">Semicertain.com</a> which, if clicked, will bring you right back here.
disqus_shortname: programming
#google_analytics: UA-31048387-6
avatar_url: /static/img/me.jpg

theme: jekyll-theme-minimal # https://github.com/pages-themes/minimal

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
#    - icon: fa-facebook
#      link: "https://www.facebook.com/tjamadar"
    - icon: fa-twitter
      link: "https://twitter.com/Semicertain"
#    - icon: fa-linkedin
#      link: "https://www.linkedin.com/in/tauseef-jamadar-5b577913/"
#     - icon: fa-stack-exchange
#       link: "#"
    - icon: fa-github
      link: "https://github.com/semicertain"

share:
  twitter_username: semicertain
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
url: "https://semicertain.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
